export default {
  linkModalTeamRef: document.querySelector('.js-modal-team'),
  btnLogOut: document.querySelector('.js-log-out'),
  btnHomeRef: document.querySelector('.js-home'),
  btnLybraryRef: document.querySelector('.js-lybrary'),
  btnAuthRef: document.querySelector('.js-auth'),
  logoRef: document.querySelector('.js-logo'),
  watchedBtnRef: document.querySelector('.js-button-watched'),
  queueBtnRef: document.querySelector('.js-button-queue'),
  paginationCase: document.getElementById('tui-pagination-container'),
  inputFormRef: document.querySelector('.js-search-form'),
  listUlFilms: document.querySelector('.js-film-list'),
  header: document.querySelector('header'),
  footer: document.querySelector('footer'),
  main: document.querySelector('main'),
  modalContainer: document.querySelector('.card__js-killer-container--modal'),

  blockLoginRef: document.querySelector('.js-auth-button'),

  modalRef: document.querySelector('.modal'),
  modalCardRef: document.querySelector('.card__container--modal'),

  // list: document.querySelector('.js-film-list'),
  btnClose: document.querySelector('.modal__button'),
  backdrop: document.querySelector('.backdrop'),
  itemAddWatched: document.querySelector('.js-add-watched'),
  itemRemoveWatched: document.querySelector('.js-remove-watched'),
  itemAddQueue: document.querySelector('.js-add-queue'),
  itemRemoveQueue: document.querySelector('.js-remove-queue'),
  buttonContainer: document.querySelector('.button-container'),
  buttonGetVideos: document.querySelector('.js-add-video'),
  trailerContainer: document.querySelector('.js-video-trailer'),
};
